name: tlb_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.1
  transparent_image: ^2.0.1
  png_optimizer: ^0.0.1-pre.0
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.6
  dropdown_button2: ^2.3.9
  dio: ^5.7.0
  http: ^1.2.2
  go_router: ^14.6.0
  fpdart: ^1.1.1
  get_it: ^8.0.2
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  webview_flutter: ^4.2.1
  mobile_scanner: ^6.0.2
  flutter_gemini: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - path: lib/assets/images/
      transformers:
        - package: png_optimizer

flutter_native_splash:
  android: true
  ios: true
  web: false

  background_image: "lib/assets/splash/background_image.png"
  image: "lib/assets/splash/foreground_logo.png"

  android_12:
    color: "#588b78"
    image: "lib/assets/splash/foreground_logo.png"
    icon_background_color: "#588b78"
